base_images:
  base:
    name: "4.9"
    namespace: ocp
    tag: base
  cli:
    name: "4.9"
    namespace: ocp
    tag: cli
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile.rhel
  from: base
  to: cluster-update-keys
promotion:
  name: "4.9"
  namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.9"
  namespace: ocp
tests:
- as: e2e-aws
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: e2e-aws-upgrade
  steps:
    cluster_profile: aws
    workflow: openshift-upgrade-aws
- as: verify-configmaps
  commands: bash hack/verify-configmaps.sh
  container:
    from: cli
zz_generated_metadata:
  branch: master
  org: openshift
  repo: cluster-update-keys
